name: unit-test
on:
  push:
    branches:
      - feature-prj-config

jobs:
  setup environment:
    name: setup - ${{ matrix.os }} - ${{ matrix.node-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        os: [windows-latest, windows-2016, ubuntu-latest, ubuntu-18.04, macos-latest]

    steps:
    - name: checkout dev commits
      uses: actions/checkout@v2

    - name: use node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: restore
      uses: actions/cache@v2
      with:
        path: |
          node_modules
          */*/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/package.json') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.node-version }}-nodemodules-
      
    - name: install npm libraries
      run: npm i

  unit test:
    needs: setup environment
    name: unit test - ${{ matrix.os }} - ${{ matrix.node-version }}
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
          node-version: [12.x, 14.x, 16.x]
          os: [windows-latest, windows-2016, ubuntu-latest, ubuntu-18.04, macos-latest]

    steps:
      - name: checkout dev commits
        uses: actions/checkout@v2

      - name: use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: load node_modules
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package.json') }}

      - name: run npm unit testcases
        run: npm test